# ---------- Build ----------
FROM rust:1.83-bookworm AS builder
WORKDIR /app

# Install build-essential for C++ compilation (Tesseract-rs needs this)
RUN apt-get update && apt-get install -y cmake clang build-essential

# Cache dependencies
COPY backend/Cargo.toml backend/Cargo.lock ./
RUN mkdir src && echo "fn main(){}" > src/main.rs
RUN cargo build --release
RUN rm -rf src

COPY backend .
RUN cargo build --release

# ---------- Runtime ----------
FROM debian:bookworm-slim
WORKDIR /app

# Install runtime libraries for Tesseract and Images
RUN apt-get update && apt-get install -y \
    ca-certificates \
    libtesseract5 \
    libleptonica-dev \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/backend /app/backend
COPY backend/entrypoint.sh ./

RUN chmod +x entrypoint.sh

EXPOSE 8080
ENTRYPOINT ["./entrypoint.sh"]
CMD ["./backend"]