services:
  postgres:
    image: postgres:16
    env_file:
      - env/backend.prod.env
    volumes:
      - postgresDb:/var/lib/postgresql/data

  redis:
    image: redis:7

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile.prod
    env_file:
      - env/backend.prod.env
    ports:
      - "8088:8088"
    volumes:
      - ./backend/assets:/app/assets
    depends_on:
      - postgres
      - redis
      - mailserver

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: gaby15103.org
    ports:
      - "25:25"    # SMTP (Inbound/Relay)
      - "587:587"  # Submission (STARTTLS - What your backend uses)
      - "993:993"  # IMAP (If you want to check mail in an app)
    volumes:
      - maildata:/var/mail/
      - mailstate:/var/mail-state/
      - mailconfig:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=0 # Disabled to save RAM (ClamAV is heavy)
      - ENABLE_FAIL2BAN=1
      - SSL_TYPE=letsencrypt
      - SPOOF_PROTECTION=1
    restart: always

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile.prod
      args:
        - VITE_API_URL=https://recipes.gaby15103.org
        - VITE_STATIC_URL=https://recipes.gaby15103.org/api
    ports:
      - "80:80"
    depends_on:
      - backend

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    runtime: nvidia
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
    environment:
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
  
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: gabrielmorin03@outlook.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - postgres

  translator:
    image: libretranslate/libretranslate:latest
    container_name: translator
    ports:
      - "5000:5000"
    environment:
      - LT_LOAD_ONLY=en,fr

volumes:
  postgresDb:
  ollama_data:
  maildata:
  mailstate:
  mailconfig:
