//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::email_verification_tokens::Entity as EmailVerificationTokens;
pub use super::favorites::Entity as Favorites;
pub use super::ingredient_group_translations::Entity as IngredientGroupTranslations;
pub use super::ingredient_groups::Entity as IngredientGroups;
pub use super::ingredient_translations::Entity as IngredientTranslations;
pub use super::ingredients::Entity as Ingredients;
pub use super::languages::Entity as Languages;
pub use super::recipe_analytics::Entity as RecipeAnalytics;
pub use super::recipe_comments::Entity as RecipeComments;
pub use super::recipe_ingredient_translations::Entity as RecipeIngredientTranslations;
pub use super::recipe_ingredients::Entity as RecipeIngredients;
pub use super::recipe_ratings::Entity as RecipeRatings;
pub use super::recipe_tags::Entity as RecipeTags;
pub use super::recipe_translations::Entity as RecipeTranslations;
pub use super::recipe_versions::Entity as RecipeVersions;
pub use super::recipes::Entity as Recipes;
pub use super::roles::Entity as Roles;
pub use super::sessions::Entity as Sessions;
pub use super::step_group_translations::Entity as StepGroupTranslations;
pub use super::step_groups::Entity as StepGroups;
pub use super::step_translations::Entity as StepTranslations;
pub use super::steps::Entity as Steps;
pub use super::tags::Entity as Tags;
pub use super::user_roles::Entity as UserRoles;
pub use super::users::Entity as Users;
