//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "recipes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub image_url: String,
    pub servings: i32,
    pub prep_time_minutes: i32,
    pub cook_time_minutes: i32,
    #[sea_orm(column_type = "Text")]
    pub author: String,
    pub author_id: Option<Uuid>,
    pub is_private: bool,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub original_language_code: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::favorites::Entity")]
    Favorites,
    #[sea_orm(has_many = "super::ingredient_groups::Entity")]
    IngredientGroups,
    #[sea_orm(
        belongs_to = "super::languages::Entity",
        from = "Column::OriginalLanguageCode",
        to = "super::languages::Column::Code",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Languages,
    #[sea_orm(has_many = "super::recipe_analytics::Entity")]
    RecipeAnalytics,
    #[sea_orm(has_many = "super::recipe_comments::Entity")]
    RecipeComments,
    #[sea_orm(has_many = "super::recipe_ratings::Entity")]
    RecipeRatings,
    #[sea_orm(has_many = "super::recipe_tags::Entity")]
    RecipeTags,
    #[sea_orm(has_many = "super::recipe_translations::Entity")]
    RecipeTranslations,
    #[sea_orm(has_many = "super::recipe_versions::Entity")]
    RecipeVersions,
    #[sea_orm(has_many = "super::step_groups::Entity")]
    StepGroups,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::AuthorId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::favorites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Favorites.def()
    }
}

impl Related<super::ingredient_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IngredientGroups.def()
    }
}

impl Related<super::languages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Languages.def()
    }
}

impl Related<super::recipe_analytics::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeAnalytics.def()
    }
}

impl Related<super::recipe_comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeComments.def()
    }
}

impl Related<super::recipe_ratings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeRatings.def()
    }
}

impl Related<super::recipe_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeTags.def()
    }
}

impl Related<super::recipe_translations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeTranslations.def()
    }
}

impl Related<super::recipe_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeVersions.def()
    }
}

impl Related<super::step_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StepGroups.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        super::recipe_tags::Relation::Tags.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::recipe_tags::Relation::Recipes.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
