//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "step_group_translations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub step_group_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub language_code: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::languages::Entity",
        from = "Column::LanguageCode",
        to = "super::languages::Column::Code",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Languages,
    #[sea_orm(
        belongs_to = "super::step_groups::Entity",
        from = "Column::StepGroupId",
        to = "super::step_groups::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    StepGroups,
}

impl Related<super::languages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Languages.def()
    }
}

impl Related<super::step_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StepGroups.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
