//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "ingredient_units")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub code: String,
    pub symbol: String,
    pub name_fr: String,
    pub name_en: String,
    pub system: String,
    pub base_unit_id: Option<Uuid>,
    #[sea_orm(column_type = "Double")]
    pub conversion_factor: f64,
    pub is_fraction_allowed: bool,
    pub is_active: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::BaseUnitId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::recipe_ingredients::Entity")]
    RecipeIngredients,
}

impl Related<super::recipe_ingredients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeIngredients.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
