//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "languages")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub code: String,
    pub name: String,
    pub native_name: String,
    pub is_active: bool,
    pub is_default: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ingredient_group_translations::Entity")]
    IngredientGroupTranslations,
    #[sea_orm(has_many = "super::ingredient_translations::Entity")]
    IngredientTranslations,
    #[sea_orm(has_many = "super::recipe_ingredient_translations::Entity")]
    RecipeIngredientTranslations,
    #[sea_orm(has_many = "super::recipe_translations::Entity")]
    RecipeTranslations,
    #[sea_orm(has_many = "super::recipes::Entity")]
    Recipes,
    #[sea_orm(has_many = "super::step_group_translations::Entity")]
    StepGroupTranslations,
    #[sea_orm(has_many = "super::step_translations::Entity")]
    StepTranslations,
}

impl Related<super::ingredient_group_translations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IngredientGroupTranslations.def()
    }
}

impl Related<super::ingredient_translations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IngredientTranslations.def()
    }
}

impl Related<super::recipe_ingredient_translations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeIngredientTranslations.def()
    }
}

impl Related<super::recipe_translations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeTranslations.def()
    }
}

impl Related<super::recipes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recipes.def()
    }
}

impl Related<super::step_group_translations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StepGroupTranslations.def()
    }
}

impl Related<super::step_translations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StepTranslations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
