//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "recipe_ingredient_translations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "unique_recipe_ingredient_language")]
    pub recipe_ingredient_id: Uuid,
    #[sea_orm(column_type = "Text", unique_key = "unique_recipe_ingredient_language")]
    pub language_code: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub note: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::languages::Entity",
        from = "Column::LanguageCode",
        to = "super::languages::Column::Code",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Languages,
    #[sea_orm(
        belongs_to = "super::recipe_ingredients::Entity",
        from = "Column::RecipeIngredientId",
        to = "super::recipe_ingredients::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    RecipeIngredients,
}

impl Related<super::languages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Languages.def()
    }
}

impl Related<super::recipe_ingredients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeIngredients.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
