//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "recipe_ingredients")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub ingredient_group_id: Uuid,
    pub ingredient_id: Uuid,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub quantity: Decimal,
    pub position: i32,
    pub unit_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ingredient_groups::Entity",
        from = "Column::IngredientGroupId",
        to = "super::ingredient_groups::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IngredientGroups,
    #[sea_orm(
        belongs_to = "super::ingredient_units::Entity",
        from = "Column::UnitId",
        to = "super::ingredient_units::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    IngredientUnits,
    #[sea_orm(
        belongs_to = "super::ingredients::Entity",
        from = "Column::IngredientId",
        to = "super::ingredients::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ingredients,
    #[sea_orm(has_many = "super::recipe_ingredient_translations::Entity")]
    RecipeIngredientTranslations,
}

impl Related<super::ingredient_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IngredientGroups.def()
    }
}

impl Related<super::ingredient_units::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IngredientUnits.def()
    }
}

impl Related<super::ingredients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ingredients.def()
    }
}

impl Related<super::recipe_ingredient_translations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeIngredientTranslations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
