//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "step_translations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "unique_step_language")]
    pub step_id: Uuid,
    #[sea_orm(unique_key = "unique_step_language")]
    pub language_code: String,
    pub instruction: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::languages::Entity",
        from = "Column::LanguageCode",
        to = "super::languages::Column::Code",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Languages,
    #[sea_orm(
        belongs_to = "super::steps::Entity",
        from = "Column::StepId",
        to = "super::steps::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Steps,
}

impl Related<super::languages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Languages.def()
    }
}

impl Related<super::steps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Steps.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
