//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "steps")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "unique")]
    pub step_group_id: Uuid,
    #[sea_orm(unique_key = "unique")]
    pub position: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub image_url: Option<String>,
    pub duration_minutes: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::step_groups::Entity",
        from = "Column::StepGroupId",
        to = "super::step_groups::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    StepGroups,
    #[sea_orm(has_many = "super::step_translations::Entity")]
    StepTranslations,
}

impl Related<super::step_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StepGroups.def()
    }
}

impl Related<super::step_translations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StepTranslations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
