//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    pub username: String,
    pub first_name: String,
    pub last_name: String,
    pub password_hash: String,
    pub avatar_url: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub preferences: Json,
    pub is_active: bool,
    pub email_verified: bool,
    pub last_login_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub two_factor_secret: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub two_factor_recovery_codes: Option<Json>,
    pub two_factor_confirmed_at: Option<DateTime>,
    pub two_factor_token: Option<Uuid>,
    pub two_factor_token_expires_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::email_verification_tokens::Entity")]
    EmailVerificationTokens,
    #[sea_orm(has_many = "super::favorites::Entity")]
    Favorites,
    #[sea_orm(has_many = "super::password_reset_tokens::Entity")]
    PasswordResetTokens,
    #[sea_orm(has_many = "super::recipe_analytics::Entity")]
    RecipeAnalytics,
    #[sea_orm(has_many = "super::recipe_comments::Entity")]
    RecipeComments,
    #[sea_orm(has_many = "super::recipe_ratings::Entity")]
    RecipeRatings,
    #[sea_orm(has_many = "super::recipe_versions::Entity")]
    RecipeVersions,
    #[sea_orm(has_many = "super::recipes::Entity")]
    Recipes,
    #[sea_orm(has_many = "super::sessions::Entity")]
    Sessions,
    #[sea_orm(has_many = "super::user_roles::Entity")]
    UserRoles,
}

impl Related<super::email_verification_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EmailVerificationTokens.def()
    }
}

impl Related<super::favorites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Favorites.def()
    }
}

impl Related<super::password_reset_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PasswordResetTokens.def()
    }
}

impl Related<super::recipe_analytics::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeAnalytics.def()
    }
}

impl Related<super::recipe_comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeComments.def()
    }
}

impl Related<super::recipe_ratings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeRatings.def()
    }
}

impl Related<super::recipe_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeVersions.def()
    }
}

impl Related<super::recipes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recipes.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl Related<super::user_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRoles.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_roles::Relation::Roles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_roles::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
