//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod email_verification_tokens;
pub mod favorites;
pub mod ingredient_group_translations;
pub mod ingredient_groups;
pub mod ingredient_translations;
pub mod ingredients;
pub mod languages;
pub mod password_reset_tokens;
pub mod recipe_analytics;
pub mod recipe_comments;
pub mod recipe_ingredient_translations;
pub mod recipe_ingredients;
pub mod recipe_ratings;
pub mod recipe_tags;
pub mod recipe_translations;
pub mod recipe_versions;
pub mod recipes;
pub mod roles;
pub mod sessions;
pub mod step_group_translations;
pub mod step_groups;
pub mod step_translations;
pub mod steps;
pub mod tags;
pub mod user_roles;
pub mod users;
